### ISSUE TITLE
Connection Fails

### ISSUE THREAD

**Issue by MaKaNu** [joshikstr/driverThorlabsLTS#3]
Hi,

Die Funktion `lts_1.connect(SN{1})` bzw. `connect(lts_1, SN{1}) scheitert mit einem etwas wenig aussagenden Fehler:

```matlab
Error using LTS/connect (line 80)
Message: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
Source: Thorlabs.MotionControl.PrivateInternal
HelpLink:
```

Dies geschieht nach deinem erfolgrecihen Test der Seriennummer. Demnach wird zwar das Device korrekt erkannt, aber das `DeviceNET` kann nicht erzeugt werden. Kennst du das Problem?

**Comment by MaKaNu** [comment]
Nach der Treiberinstallation ist es wohl notwendig den PC neuzustarten.

**Comment by joshikstr** [comment]
Device must be enabled after connection: 
```matlab
lts_1 = LTS;
lts_1.connect(SNR)
lts_1.deviceNET.EnableDevice()
```

**Comment by joshikstr** [comment]
bugfix in the last commit
